openapi: 3.0.0
info:
  title: News Aggregator API
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
  /auth/signup:
    post:
      summary: User signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignup'
      responses:
        '200':
          description: Signup successful
        '400':
          description: User already exists
components:
  schemas:
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    UserSignup:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string